/* 杭州探索録3 Definitive Edition Ver.1.3 — HANGZHOU METRO */
let metroOpen=false;
let metroSelected=null;
const metroPanel=document.createElement("div");metroPanel.id="metroPanel";metroPanel.className="v12-panel metro-v13 hidden";document.getElementById("game").appendChild(metroPanel);
function nearestMetro(){if(scene!=="city")return null;const s=METRO_STATIONS[currentMapId];if(!s)return null;return dist(player.x,player.y,s.x,s.y)<125?s:null;}
function openMetro(){metroOpen=true;metroSelected=currentMapId;keys.w=keys.a=keys.s=keys.d=keys.arrowup=keys.arrowdown=keys.arrowleft=keys.arrowright=false;renderMetro();metroPanel.classList.remove("hidden");}
function closeMetro(){metroOpen=false;metroPanel.classList.add("hidden");}
function routeFor(from,to){if(from===to)return[];const f=METRO_STATIONS[from],t=METRO_STATIONS[to];const common=f.lines.find(x=>t.lines.includes(x));if(common)return[{line:common,from,to}];
 // Game-network transfer logic: Wulin is the hub for L1/L3; Civic Center links the southern L4/L7 branch.
 if(from==="qianjiang"||to==="qianjiang"){const other=from==="qianjiang"?to:from;return from==="qianjiang"?[{line:"L4",from:"qianjiang",to:"wulin"},{line:"L1",from:"wulin",to:other}]:[{line:"L1",from:other,to:"wulin"},{line:"L4",from:"wulin",to:"qianjiang"}];}
 return[{line:"L1",from,to}];}
function lineBadges(s){return s.lines.map(id=>`<i class="line-badge" style="--c:${METRO_LINES[id].color}">${METRO_LINES[id].short}</i>`).join("");}
function renderMetro(){
 const current=METRO_STATIONS[currentMapId];
 metroPanel.innerHTML=`<div class="v12-head"><span>杭州地铁 · 夜行路線図</span><button data-close>×</button></div><div class="v12-sub">HANGZHOU METRO / NIGHT EXPLORER · ${current.name} ${current.exit}口</div>
 <div class="metro-map-wrap"><div class="metro-map-title"><b>深夜探索線</b><span>駅を選択してください</span></div><div class="metro-map" id="metroMap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path class="track l1" d="M22 48 L50 22 L76 48"/><path class="track l4" d="M50 78 L50 22"/><circle class="transfer" cx="50" cy="22" r="4.2"/></svg>${Object.entries(METRO_STATIONS).map(([id,s])=>`<button class="map-station ${id===currentMapId?"current":""}" style="--x:${s.mapX}%;--y:${s.mapY}%;--c:${s.color}" data-map="${id}"><span class="map-dot"></span><b>${s.name}</b><small>${s.lines.map(x=>METRO_LINES[x].short).join("·")}</small></button>`).join("")}</div><div class="metro-legend"><span><i style="--c:${METRO_LINES.L1.color}"></i>1号线</span><span><i style="--c:${METRO_LINES.L3.color}"></i>3号线</span><span><i style="--c:${METRO_LINES.L4.color}"></i>4号线</span><span><i style="--c:${METRO_LINES.L7.color}"></i>7号线</span></div></div>
 <div id="metroRoute" class="metro-route"></div><div class="metro-list">${Object.entries(METRO_STATIONS).map(([id,s])=>`<button class="metro-stop ${id===currentMapId?"current":""}" data-list-map="${id}"><span class="badges">${lineBadges(s)}</span><span><b>${s.name}</b><small>${s.en} · ${MAPS[id].name} · ${s.exit}口</small></span><em>${id===currentMapId?"現在地":"選択"}</em></button>`).join("")}</div><div class="v12-foot">路線図または駅名を選択 → 経路確認 → 乗車</div>`;
 metroPanel.querySelector("[data-close]").onclick=closeMetro;
 metroPanel.querySelectorAll("[data-map],[data-list-map]").forEach(b=>b.onclick=()=>selectMetro(b.dataset.map||b.dataset.listMap));selectMetro(metroSelected,false);
}
function selectMetro(id,rerender=true){metroSelected=id;const target=METRO_STATIONS[id],box=metroPanel.querySelector("#metroRoute");if(!box)return;metroPanel.querySelectorAll(".map-station,.metro-stop").forEach(x=>x.classList.toggle("selected",(x.dataset.map||x.dataset.listMap)===id));
 if(id===currentMapId){box.innerHTML=`<div><strong>${target.name}</strong><small>現在地です</small></div>`;return;}
 const route=routeFor(currentMapId,id);const routeHtml=route.map((r,i)=>{const ln=METRO_LINES[r.line];return `${i?'<span class="transfer-text">乗換</span>':''}<span class="route-seg"><i style="--c:${ln.color}">${ln.short}</i>${METRO_STATIONS[r.from].name} → ${METRO_STATIONS[r.to].name}</span>`}).join("");box.innerHTML=`<div class="route-copy"><strong>${METRO_STATIONS[currentMapId].name} → ${target.name}</strong><small>${routeHtml}</small></div><button class="ride-button">この経路で乗車</button>`;box.querySelector(".ride-button").onclick=()=>metroTravel(id);
}
let metroRideOverlay=null;function ensureMetroRideOverlay(){if(metroRideOverlay)return metroRideOverlay;metroRideOverlay=document.createElement("div");metroRideOverlay.id="metroRideOverlay";metroRideOverlay.className="metro-ride hidden";metroRideOverlay.innerHTML=`<div class="ride-city">杭州地铁</div><div class="ride-window"><div class="tunnel-lights"></div><div class="train-body"><i></i><i></i><i></i><i></i><i></i></div></div><div class="ride-route"></div>`;document.getElementById("game").appendChild(metroRideOverlay);return metroRideOverlay;}function metroTravel(mapId){const s=METRO_STATIONS[mapId];if(!s||mapId===currentMapId)return;const from=METRO_STATIONS[currentMapId];closeMetro();const ov=ensureMetroRideOverlay();ov.querySelector(".ride-route").textContent=`${from.name}  →  ${s.name}`;ov.classList.remove("hidden");setTimeout(()=>{switchMapData(mapId);player.x=s.x;player.y=s.y+145;camera.x=player.x;camera.y=player.y;transitionLock=1.2;updateLocationUI();showDistrictCard();if(typeof journalState!=="undefined"){journalState.metroTrips=(journalState.metroTrips||0)+1;saveJournal();markMapVisited();}if(typeof acquireByCategory==="function")acquireByCategory("地下鉄",`地铁：${from.name}→${s.name}`);fade.active=true;fade.phase="in";fade.alpha=1;fade.target=null;ov.classList.add("hidden");},2000);}const _metroUpdateInteraction=updateInteraction;updateInteraction=function(){_metroUpdateInteraction();const s=nearestMetro();if(s){interactionTarget={type:"metro",station:s};interactionBox.classList.remove("hidden");interactionText.textContent=`地铁 ${s.name} ${s.exit}口`;}};
const _metroInteract=interact;interact=function(){if(interactionTarget?.type==="metro"){openMetro();return;}_metroInteract();};const _metroUpdatePlayer=updatePlayer;updatePlayer=function(dt){if(metroOpen||!journal.classList.contains("hidden"))return;_metroUpdatePlayer(dt);};
window.addEventListener("keydown",e=>{if(e.key==="Escape"&&metroOpen)closeMetro();});
